chronos/accounts/urls.py
from django.urls import path

from chronos.accounts import views


urlpatterns = [
    path('register/', views.register_account, name='register_account'),
    path('login/', views.login_user, name='login_account'),
    path('logout/', views.logout_user, name='logout_account'),
    path('show/', views.show_account, name='show_account'),
    path('edit/', views.edit_account, name='edit_account'),
    path('delete/', views.delete_account, name='delete_account'),

    # path('register/', RegisterView.as_view(), name='register profile'),
]

chronos/posts/urls.py
from django.urls import path

from chronos.posts import views

urlpatterns = [
    path('all/', views.show_posts, name='show_posts'),
    path('details/<int:pk>', views.show_post, name='show_post'),
]

chronos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('chronos.web.urls', 'chronos.web.urls'), namespace='web')),
    path('accounts/', include(('chronos.accounts.urls', 'chronos.accounts.urls'), namespace='accounts')),
    path('posts/', include(('chronos.posts.urls', 'chronos.posts.urls'), namespace='posts')),
    path('watches/', include(('chronos.watches.urls', 'chronos.watches.urls'), namespace='watches')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chronos/watches/urls.py
from django.urls import path

from chronos.watches import views

urlpatterns = [
    path('add/', views.add_watch, name='add_watch'),
    path('all/', views.show_all_watches, name='show_all_watches'),
    path('collection/', views.show_my_watches, name='show_collection'),
    path('details/<int:pk>', views.show_watch, name='show_watch'),
    path('edit/<int:pk>', views.edit_watch, name='edit_watch'),
    path('delete/<int:pk>', views.delete_watch, name='delete_watch'),
    path('like/<int:pk>', views.like_watch, name='like_watch'),
]

chronos/web/urls.py
from django.urls import path

from chronos.web import views

urlpatterns = [
    path('', views.show_homepage, name='show_homepage'),
]

chronos/web/templates/web/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CHRONOS</title>

    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <link rel="shortcut icon" href="{% static 'favicon.png' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>

</head>

<body class="d-flex flex-column min-vh-100">

{% include 'web/navigation.html' %}

{% include 'web/messages.html' %}

{% block content %}
{% endblock %}

{% include 'web/footer.html' %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'js/scripts.js' %}"></script>
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
</html>

chronos/web/templates/web/footer.html
<footer class="footer py-1 mt-auto" style="background-color: #2a2a2a; color: white">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-4 text-lg-start">Erin Bedri 2022</div>
            <div class="col-lg-4 my-3 my-lg-0"></div>
            <div class="col-lg-4 text-lg-end">
                <a class="link-dark text-decoration-none me-3" href="#">Privacy Policy</a>
                <a class="link-dark text-decoration-none" href="#">Terms of Use</a>
            </div>
        </div>
    </div>
</footer>

chronos/web/templates/web/homepage.html
{% extends 'web/base.html' %}
{% load static %}

{% block content %}

    <div class="row d-flex justify-content-center" style="margin-top: 30px">
        <div class="col-sm-10">
            <h2 style="margin-bottom: 30px">Chronos - the watch collector's platform...</h2>
            <p>Not every watch has to come fresh from the factory. In fact, many people fall for the charm of watches
                with designs from the 60s or 70s. These vintage watches include coveted collector's items and hidden
                treasures waiting to be uncovered by watch fans.</p>
            <div class="text-center" style="margin-top: 30px; margin-bottom: 30px">
                <img src="{% static 'img/longines_vintage.jpg' %}" class="img-fluid" size="200x200px">
            </div>
            <p>Searching for the right vintage watch is part of the overall collecting experience and often turns
                novices into watch aficionados.</p>
            <p>On <b>Chronos</b> you can share your collection with other watch enthusiasts, read watch related
                articles, discuss and interact with other like-minded.
            <p><a href="{% url 'accounts:register_account' %}">Register now</a> and start your watch collecting journey.</p></p>
        </div>
    </div>

{% endblock %}

chronos/web/templates/web/messages.html
<div class="row d-flex justify-content-center" style="margin-top: 90px">
    <div class="col-md-11">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags != 'error' %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                             class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16"
                             role="img"
                             aria-label="Warning:">
                            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                        </svg>
                        <strong>{{ message|striptags }}</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
</div>

chronos/web/templates/web/navigation.html
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'web:show_homepage' %}">CHRONOS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                           style="color: #FFC107">Welcome, {{ request.user.username }}</a>
                    </li>
                {% endif %}

                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'posts:show_posts' %}">Posts</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'watches:show_all_watches' %}">All Watches</a>
                </li>

                {% if user.is_authenticated %}

                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'watches:add_watch' %}">Add Watch</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'watches:show_collection' %}">My
                            Collection</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'accounts:show_account' %}">Profile</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'accounts:logout_account' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'accounts:login_account' %}">Login</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'accounts:register_account' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>