chronos/accounts/urls.py
from django.urls import path

from chronos.accounts import views


urlpatterns = [
    path('register/', views.register_account, name='register_account'),
    path('login/', views.login_user, name='login_account'),
    path('logout/', views.logout_user, name='logout_account'),
    path('show/', views.show_account, name='show_account'),
    path('edit/', views.edit_account, name='edit_account'),
    path('delete/', views.delete_account, name='delete_account'),

    # path('register/', RegisterView.as_view(), name='register profile'),
]

chronos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('chronos.web.urls', 'chronos.web.urls'), namespace='web')),
    path('accounts/', include(('chronos.accounts.urls', 'chronos.accounts.urls'), namespace='accounts')),
    path('posts/', include(('chronos.posts.urls', 'chronos.posts.urls'), namespace='posts')),
    path('watches/', include(('chronos.watches.urls', 'chronos.watches.urls'), namespace='watches')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chronos/web/urls.py
from django.urls import path

from chronos.web import views

urlpatterns = [
    path('', views.show_homepage, name='show_homepage'),
]

chronos/accounts/models.py
# from django.contrib.auth import get_user_model
# from django.db import models
# from django.db.models import CASCADE
#
# UserModel = get_user_model()
#
#
# class Profile(models.Model):
#     PROFILE_BIO_MAX_LEN = 250
#
#     user = models.ForeignKey(
#         UserModel,
#         primary_key=True,
#         on_delete=CASCADE,
#     )
#
#     bio = models.TextField(
#         blank=True,
#         null=True,
#         max_length=PROFILE_BIO_MAX_LEN,
#     )
#
#     image = models.ImageField(
#         blank=True,
#         null=True,
#         upload_to='profile_image/',
#         default='img/default_profile_img.jpeg',
#     )

chronos/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


UserModel = get_user_model()


class RegisterUserForm(UserCreationForm):
    first_name = forms.CharField(required=True,
                                 max_length=30,
                                 widget=forms.TextInput(attrs={'placeholder': 'First Name',
                                                               'class': 'form-control',
                                                               }))
    last_name = forms.CharField(required=True,
                                max_length=30,
                                widget=forms.TextInput(attrs={'placeholder': 'Last Name',
                                                              'class': 'form-control',
                                                              }))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'placeholder': 'Email Address',
                                                           'class': 'form-control',
                                                           }))
    username = forms.CharField(required=True,
                               max_length=30,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
    password1 = forms.CharField(required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))
    password2 = forms.CharField(required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))

    class Meta:
        model = UserModel
        fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2')

    def save(self, commit=True):
        user = super(RegisterUserForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        return user

    def clean(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if User.objects.filter(email=email).exists():
            raise ValidationError('Email already exists')
        if User.objects.filter(username=username).exists():
            raise ValidationError('Username already exists')
        return self.cleaned_data


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
    password = forms.CharField(required=True,
                               widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                 'class': 'form-control',
                                                                 }))
    remember_me = forms.BooleanField(required=False)


class EditUserForm(forms.ModelForm):
    first_name = forms.CharField(required=True,
                                 max_length=30,
                                 widget=forms.TextInput(attrs={'class': 'form-control',
                                                               }))
    last_name = forms.CharField(required=True,
                                max_length=30,
                                widget=forms.TextInput(attrs={'class': 'form-control',
                                                              }))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control',
                                                           }))
    username = forms.CharField(required=True,
                               max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control',
                                                             }))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')


class DeleteUserForm(forms.ModelForm):
    class Meta:
        model = UserModel
        fields = ()

chronos/accounts/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from chronos.accounts.forms import RegisterUserForm, CustomAuthenticationForm, EditUserForm, DeleteUserForm
from chronos.watches.models import Watch

REGISTRATION_SUCCESS_MESSAGE = 'Registration successful!'

LOGIN_SUCCESS_MESSAGE = 'You are successfully logged in '
LOGIN_ERROR_MESSAGE = 'Invalid username or password!'

LOGOUT_SUCCESS_MESSAGE = 'You are successfully logged out.'

PROFILE_EDIT_SUCCESS_MESSAGE = 'You successfully updated your profile information!'

PROFILE_DELETE_SUCCESS_MESSAGE = 'You successfully deleted your profile information!'


def register_account(request):
    if request.user.is_authenticated:
        return redirect('web:show_homepage')

    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, REGISTRATION_SUCCESS_MESSAGE)
            return redirect('watches:show_all_watches')
        else:
            messages.error(request, form.errors)
    else:
        form = RegisterUserForm()

    context = {
        'form': form,
    }

    return render(request, 'accounts/register.html', context)


def login_user(request):
    if request.user.is_authenticated:
        return redirect('web:homepage')

    if request.method == 'POST':
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            remember_me = form.cleaned_data.get('remember_me')
            user = authenticate(username=username, password=password)
            if user is not None:
                if not remember_me:
                    request.session.set_expiry(0)
                    request.session.modified = True
                login(request, user)
                messages.success(request, LOGIN_SUCCESS_MESSAGE + f'as {username}!')
                return redirect('watches:show_all_watches')
            else:
                messages.error(request, LOGIN_ERROR_MESSAGE)
        else:
            messages.error(request, LOGIN_ERROR_MESSAGE)
    else:
        form = CustomAuthenticationForm()

    context = {
        'form': form,
    }

    return render(request, 'accounts/login.html', context)


@login_required
def logout_user(request):
    logout(request)
    messages.success(request, LOGOUT_SUCCESS_MESSAGE)
    return redirect('web:show_homepage')


@login_required
def show_account(request):
    watch_count = Watch.objects.filter(owner=request.user).count()
    total_paid = sum(
        [watch.price_paid if watch.price_paid is not None else 0
         for watch in Watch.objects.filter(owner=request.user)])

    context = {
        'watch_count': watch_count,
        'total_paid': total_paid,
    }

    return render(request, 'accounts/details.html', context)


@login_required
def edit_account(request):
    if request.method == 'POST':
        form = EditUserForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, PROFILE_EDIT_SUCCESS_MESSAGE)
            return redirect('accounts:show_account')
        else:
            messages.error(request, form.errors)
    else:
        form = EditUserForm(instance=request.user)

    context = {
        'form': form
    }

    return render(request, 'accounts/edit.html', context)


@login_required
def delete_account(request):
    if request.method == 'POST':
        form = DeleteUserForm(request.POST, instance=request.user)
        if form.is_valid():
            request.user.delete()
            messages.success(request, PROFILE_DELETE_SUCCESS_MESSAGE)
            return redirect('web:show_homepage')
    else:
        form = DeleteUserForm(instance=request.user)

    context = {
        'form': form
    }

    return render(request, 'accounts/delete.html', context)

chronos/accounts/templates/accounts/delete.html
{% extends 'web/base.html' %}

{% block content %}
        <div class="row d-flex justify-content-center" style="margin-top: 50px">
            <div class="col-md-5">
                <form id="delete" method="POST" action="{% url 'accounts:delete_account' %}">
                    <div class="container">

                        <h3>Are you sure you want to delete your profile?</h3>

                        {% csrf_token %}
                        {{ form }}

                        <input class="btn btn-danger flex-grow-1" type="submit" value="Delete Profile"
                               style="margin-top: 20px">
                        <button type="button" onclick="location.href='{% url 'web:show_homepage' %}'"
                                class="btn btn-secondary flex-grow-1" style="margin-top: 20px">Cancel
                        </button>
                    </div>
                </form>
            </div>
        </div>
{% endblock %}

chronos/accounts/templates/accounts/details.html
{% extends 'web/base.html' %}
{% load humanize %}

{% block content %}

    {% if request.user.is_authenticated %}

        <div class="container py-5 h-40">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col col-md-9 col-lg-7 col-xl-5">
                    <div class="card" style="border-radius: 15px;">
                        <div class="card-body p-4">
                            <div class="d-flex text-black">
                                <div class="flex-grow-1 ms-3">
                                    <h5 class="mb-1 pb-1">{{ request.user.first_name }} {{ request.user.last_name }}</h5>
                                    <p class="mb-2 pb-1" style="color: #2b2a2a;">
                                        <b>Username: </b>{{ request.user.username }}
                                    </p>
                                    <p class="mb-2 pb-1" style="color: #2b2a2a;">
                                        <b>Email: </b>{{ request.user.email }}
                                    </p>
                                    <p class="mb-2 pb-1" style="color: #2b2a2a;">
                                        <b>Watches in Collection: </b>{{ watch_count }}
                                    </p>
                                    <p class="mb-2 pb-1" style="color: #2b2a2a;">
                                        <b>Total Paid: </b>EUR {{ total_paid|floatformat:2|intcomma }}
                                    </p>
                                    <p class="mb-2 pb-1" style="color: #2b2a2a;">
                                        <b>Member Since: </b>{{ request.user.date_joined|date }}
                                    </p>
                                    <div class="d-flex pt-1">
                                        <button type="button" onclick="location.href='{% url 'accounts:edit_account' %}'"
                                                class="btn btn-warning me-1 flex-grow-1">Edit
                                        </button>
                                        <button type="button"
                                                onclick="location.href='{% url 'accounts:delete_account' %}'"
                                                class="btn btn-outline-danger flex-grow-1">Delete
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    {% endif %}

{% endblock %}

chronos/accounts/templates/accounts/edit.html
{% extends 'web/base.html' %}

{% block content %}
    <div class="container" style="margin-top: 50px">
        <div class="row justify-content-md-center">
            <div class="col-md-6">
                <h3>Edit details of your profile</h3>
                <form method="POST" action="{% url 'accounts:edit_account' %}">
                    {% csrf_token %}

                    {% if form.errors %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <div id="form_errors">
                                {% for key, value in form.errors.items %}
                                    <strong>{{ value }}</strong>
                                {% endfor %}
                            </div>
                            <strong>{{ message|striptags }}</strong>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}

                    <div class="row" style="margin-top: 30px">
                        <div class="col">
                            <label class="mb-1">First Name*</label>
                            {{ form.first_name }}
                        </div>
                        <div class="col">
                            <label class="mb-1">Last Name*</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                    <div class="row" style="margin-top: 30px">
                        <div class="col">
                            <label class="mb-1">Username*</label>
                            {{ form.username }}
                        </div>
                        <div class="col">
                            <label class="mb-1">Emails*</label>
                            {{ form.email }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-warning" style="margin-top: 30px">Edit</button>
                    <button type="button" onclick="location.href='{% url 'accounts:show_account' %}'"
                            class="btn btn-secondary flex-grow-1" style="margin-top: 30px">Cancel
                    </button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

chronos/accounts/templates/accounts/login.html
{% extends 'web/base.html' %}

{% block content %}

    <div class="container" style="margin-top: 50px">
        <div class="row justify-content-md-center">
            <div class="col-md-6">
                <h3>Login</h3>
                <form method="POST" action="{% url 'accounts:login_account' %}" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% if messages %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <div id="form_errors">
                                {% for message in messages %}
                                    <strong>{{ message }}</strong>
                                {% endfor %}
                            </div>
                            <strong>{{ message|striptags }}</strong>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}

                    <div class="col" style="margin-top: 30px">
                        <label class="mb-1">Username</label>
                        {{ form.username }}
                    </div>
                    <div class="col" style="margin-top: 30px">
                        <label class="mb-1">Password</label>
                        {{ form.password }}
                    </div>
                    <div class="col" style="margin-top: 10px">
                        {{ form.remember_me }}
                        <label> Remember me</label>
                    </div>

                    <button type="submit" class="btn btn-warning" style="margin-top: 30px">Login</button>
                </form>

                <h6 style="margin-top: 30px">If you don't have an account,
                    <a href="{% url 'accounts:register_account' %}">register</a> instead.</h6>
            </div>
        </div>
    </div>

{% endblock %}

chronos/accounts/templates/accounts/register.html
{% extends 'web/base.html' %}

{% block content %}
    <div class="container" style="margin-top: 50px">
        <div class="row justify-content-md-center">
            <div class="col-md-6">
                <h3>Register</h3>
                <form method="POST" action="{% url 'accounts:register_account' %}">
                    {% csrf_token %}

                    {% if form.errors %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <div id="form_errors">
                                {% for key, value in form.errors.items %}
                                    <strong>{{ value }}</strong>
                                {% endfor %}
                            </div>
                            <strong>{{ message|striptags }}</strong>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}

                    <div class="row" style="margin-top: 30px">
                        <div class="col">
                            <label class="mb-1">First Name*</label>
                            {{ form.first_name }}
                        </div>
                        <div class="col">
                            <label class="mb-1">Last Name*</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                    <div class="row" style="margin-top: 30px">
                        <div class="col">
                            <label class="mb-1">Username*</label>
                            {{ form.username }}
                        </div>
                        <div class="col">
                            <label class="mb-1">Email*</label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="row" style="margin-top: 30px">
                        <div class="col">
                            <label class="mb-1">Password*</label>
                            {{ form.password1 }}
                        </div>
                        <div class="col">
                            <label class="mb-1">Confirm Password*</label>
                            {{ form.password2 }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-warning" style="margin-top: 30px">Register</button>
                </form>

                <h6 style="margin-top: 30px">If you already have an account,
                    <a href="{% url 'accounts:login_account' %}">login</a> instead.</h6>

            </div>
        </div>
    </div>

{% endblock %}