chronos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('chronos.web.urls', 'chronos.web.urls'), namespace='web')),
    path('accounts/', include(('chronos.accounts.urls', 'chronos.accounts.urls'), namespace='accounts')),
    path('posts/', include(('chronos.posts.urls', 'chronos.posts.urls'), namespace='posts')),
    path('watches/', include(('chronos.watches.urls', 'chronos.watches.urls'), namespace='watches')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chronos/watches/urls.py
from django.urls import path

from chronos.watches import views

urlpatterns = [
    path('add/', views.add_watch, name='add_watch'),
    path('all/', views.show_all_watches, name='show_all_watches'),
    path('collection/', views.show_my_watches, name='show_collection'),
    path('details/<int:pk>', views.show_watch, name='show_watch'),
    path('edit/<int:pk>', views.edit_watch, name='edit_watch'),
    path('delete/<int:pk>', views.delete_watch, name='delete_watch'),
    path('like/<int:pk>', views.like_watch, name='like_watch'),
]

chronos/watches/models.py
from datetime import date

from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import CASCADE

from chronos.watches.validators import file_size


class Watch(models.Model):
    BRAND_MAX_LEN = 30

    MODEL_MAX_LEN = 30

    REFERENCE_NUMBER_MAX_LEN = 30

    YEAR_MIN_VALUE = 1800
    YEAR_MAX_VALUE = date.today().year

    WATCH_STYLES_CHOICES = [
        ('Pocket', 'Pocket'),
        ('Railroad', 'Railroad'),
        ('Dress', 'Dress'),
        ('Field', 'Field'),
        ('Aviator', 'Aviator'),
        ('Dive', 'Dive'),
        ('Racing', 'Racing'),
        ('Digital', 'Digital'),
        ('Smart ', 'Smart'),
        ('Fashion', 'Fashion'),
    ]

    STYLE_MAX_LEN = max([len(style[1]) for style in WATCH_STYLES_CHOICES])

    CONDITION_MAX_LEN = 100

    PRICE_MIN_VALUE = 0

    DESCRIPTION_MAX_LEN = 500

    owner = models.ForeignKey(
        User,
        on_delete=CASCADE
    )

    brand = models.CharField(
        max_length=BRAND_MAX_LEN,
    )

    model = models.CharField(
        max_length=MODEL_MAX_LEN,
    )

    reference_number = models.CharField(
        blank=True,
        null=True,
        max_length=REFERENCE_NUMBER_MAX_LEN,
    )

    year = models.IntegerField(
        blank=True,
        null=True,
        validators=[
            MinValueValidator(YEAR_MIN_VALUE),
            MaxValueValidator(YEAR_MAX_VALUE)],
    )

    style = models.CharField(
        max_length=STYLE_MAX_LEN,
        choices=WATCH_STYLES_CHOICES,
    )

    condition = models.TextField(
        null=True,
        blank=True,
        max_length=CONDITION_MAX_LEN,
    )

    price_paid = models.FloatField(
        null=True,
        blank=True,
        validators=[
            MinValueValidator(PRICE_MIN_VALUE)
        ]
    )

    description = models.TextField(
        null=True,
        blank=True,
        max_length=DESCRIPTION_MAX_LEN,
    )

    image = models.ImageField(
        null=True,
        blank=True,
        upload_to='watches',
        validators=(
            file_size,
        )
    )

    likes = models.ManyToManyField(
        User,
        related_name='watch_likes'
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    updated_at = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        verbose_name_plural = "watches"

    def like_count(self):
        return self.likes.count()

    def __str__(self):
        return f'{self.brand} {self.model}'


class WatchComment(models.Model):
    COMMENT_MAX_LEN = 300

    author = models.ForeignKey(
        User,
        on_delete=CASCADE,
    )
    watch = models.ForeignKey(
        Watch,
        on_delete=CASCADE,
        related_name='comments'
    )
    body = models.TextField(
        max_length=COMMENT_MAX_LEN,
    )
    created_on = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return f'Comment by {self.author}.'

chronos/watches/forms.py
from django import forms

from chronos.watches.models import Watch, WatchComment


class CreateWatchForm(forms.ModelForm):
    class Meta:
        model = Watch
        fields = ('brand', 'model', 'reference_number', 'year', 'style', 'price_paid', 'condition', 'description', 'image')
        widgets = {'brand': forms.TextInput(attrs={'class': 'form-control',
                                                   'placeholder': 'Brand',
                                                   }),
                   'model': forms.TextInput(attrs={'class': 'form-control',
                                                   'placeholder': 'Model',
                                                   }),
                   'reference_number': forms.TextInput(attrs={'class': 'form-control',
                                                              'placeholder': 'Reference Number',
                                                              }),
                   'year': forms.NumberInput(attrs={'class': 'form-control',
                                                    'placeholder': 'Year',
                                                    }),
                   'style': forms.Select(attrs={'class': 'form-control',
                                                }),
                   'price_paid': forms.NumberInput(attrs={'class': 'form-control',
                                                          'placeholder': 'Price Paid in EUR',
                                                          }),
                   'condition': forms.Textarea(attrs={'class': 'form-control',
                                                      'rows': 1,
                                                      'placeholder': 'Condition',
                                                      }),
                   'description': forms.Textarea(attrs={'class': 'form-control',
                                                        'rows': 3,
                                                        'placeholder': 'Description',
                                                        }),
                   'image': forms.FileInput(attrs={'class': 'form-control',
                                                   })}


class DeleteWatchForm(forms.ModelForm):
    class Meta:
        model = Watch
        fields = ()


class EditWatchForm(forms.ModelForm):
    class Meta:
        model = Watch
        fields = ('brand', 'model', 'reference_number', 'year', 'style', 'price_paid', 'condition', 'description', 'image')
        widgets = {'brand': forms.TextInput(attrs={'class': 'form-control',
                                                   }),
                   'model': forms.TextInput(attrs={'class': 'form-control',
                                                   }),
                   'reference_number': forms.TextInput(attrs={'class': 'form-control',
                                                              }),
                   'year': forms.NumberInput(attrs={'class': 'form-control',
                                                    }),
                   'style': forms.Select(attrs={'class': 'form-control',
                                                }),
                   'price_paid': forms.NumberInput(attrs={'class': 'form-control',
                                                          }),
                   'condition': forms.Textarea(attrs={'class': 'form-control',
                                                      'rows': 1,
                                                      }),
                   'description': forms.Textarea(attrs={'class': 'form-control',
                                                        'rows': 3,
                                                        }),
                   'image': forms.FileInput(attrs={'class': 'form-control',
                                                   })}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['price_paid'].label = 'Price paid in EUR'


class WatchCommentForm(forms.ModelForm):
    class Meta:
        model = WatchComment
        fields = ('body',)
        widgets = {'body': forms.Textarea(attrs={'class': 'form-control',
                                                 'placeholder': 'Your comment',
                                                 'rows': 2,
                                                 })}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['body'].label = ''

chronos/watches/views.py
import os

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from chronos.watches.forms import CreateWatchForm, WatchCommentForm, EditWatchForm, DeleteWatchForm
from chronos.watches.models import Watch, WatchComment

WATCH_ADD_SUCCESS_MESSAGE = 'The watch was successfully added!'

WATCH_EDIT_SUCCESS_MESSAGE = 'The watch was successfully updated!'

WATCH_DELETE_SUCCESS_MESSAGE = 'The watch was successfully deleted!'

WATCHES_PER_PAGE = 8


def show_all_watches(request):
    q = request.GET.get('q') if request.GET.get('q') is not None else ''

    watches_list = Watch.objects \
        .filter(
            Q(brand__icontains=q) |
            Q(model__icontains=q) |
            Q(style__icontains=q) |
            Q(year__icontains=q) |
            Q(condition__icontains=q) |
            Q(description__icontains=q) |
            Q(owner__username=q)) \
        .order_by('-created_at')

    brands = {watch.brand for watch in Watch.objects.all()}
    styles = {watch.style for watch in Watch.objects.all()}

    paginator = Paginator(watches_list, WATCHES_PER_PAGE)

    page_number = request.GET.get('page')

    try:
        watches = paginator.page(page_number)
    except PageNotAnInteger:
        watches = paginator.page(1)
    except EmptyPage:
        watches = paginator.page(paginator.num_pages)

    context = {
        'watches': watches,
        'brands': brands,
        'styles': styles,
    }

    return render(request, 'watches/show_all.html', context)


def show_my_watches(request):
    watches = Watch.objects.filter(owner_id=request.user.id).order_by('created_at')
    total_price_paid = sum([watch.price_paid if watch.price_paid is not None else 0 for watch in watches])

    context = {
        'watches': watches,
        'total_price_paid': total_price_paid,
    }

    return render(request, 'watches/show_collection.html', context)


@login_required
def add_watch(request):
    if request.method == 'POST':
        form = CreateWatchForm(request.POST, request.FILES)
        if form.is_valid():
            watch = form.save(commit=False)
            watch.owner = request.user
            watch.save()
            messages.success(request, WATCH_ADD_SUCCESS_MESSAGE)
            return redirect('watches:show_all_watches')
        else:
            messages.error(request, form.errors)
    else:
        form = CreateWatchForm()

    context = {
        'form': form,
    }

    return render(request, 'watches/add.html', context)


def show_watch(request, pk):
    watch = get_object_or_404(Watch, pk=pk)
    comments = WatchComment.objects.filter(watch_id=pk).order_by('created_on')
    comment_count = WatchComment.objects.filter(watch_id=pk).count()
    like_count = Watch.like_count(watch)

    liked = False
    if watch.likes.filter(id=request.user.id).exists():
        liked = True

    if request.method == 'POST':
        form = WatchCommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.watch = watch
            new_comment.author = request.user
            new_comment.save()
            return redirect('watches:show_watch', pk)
    else:
        form = WatchCommentForm()

    context = {
        'watch': watch,
        'comment_form': form,
        'comments': comments,
        'comment_count': comment_count,
        'like_count': like_count,
        'liked': liked,
    }
    return render(request, 'watches/details.html', context)


@login_required
def edit_watch(request, pk):
    watch = get_object_or_404(Watch, pk=pk)

    if request.user != watch.owner:
        return render(request, '403.html')

    if request.method == 'POST':
        form = EditWatchForm(request.POST, request.FILES, instance=watch)
        if form.is_valid():
            form.save()
            messages.success(request, WATCH_EDIT_SUCCESS_MESSAGE)
            return redirect('watches:show_watch', pk)
    else:
        form = EditWatchForm(instance=watch)

    context = {
        'watch': watch,
        'form': form
    }

    return render(request, 'watches/edit.html', context)


@login_required
def delete_watch(request, pk):
    watch = get_object_or_404(Watch, pk=pk)

    if request.user != watch.owner:
        return render(request, '403.html')

    if request.method == 'POST':
        form = DeleteWatchForm(request.POST, request.FILES, instance=watch)
        if form.is_valid():
            if watch.image:
                image_path = watch.image.path
                os.remove(image_path)
            watch.delete()
            messages.success(request, WATCH_DELETE_SUCCESS_MESSAGE)
            return redirect('watches:show_all_watches')
    else:
        form = DeleteWatchForm(instance=watch)

    context = {
        'watch': watch,
        'form': form
    }

    return render(request, 'watches/delete.html', context)


@login_required
def like_watch(request, pk):
    watch = get_object_or_404(Watch, pk=pk)
    liked = False

    if watch.likes.filter(id=request.user.id).exists():
        watch.likes.remove(request.user)
        liked = False
    else:
        watch.likes.add(request.user)
        liked = True

    return HttpResponseRedirect(reverse('watches:show_watch', args=[str(pk)]))

chronos/watches/templates/watches/add.html
{% extends 'web/base.html' %}

{% block content %}
    <div class="container" style="margin-top: 30px; margin-bottom: 50px">
        <div class="row justify-content-md-center">
            <div class="col-md-6">
                <h3>Add a new watch to your collection</h3>
                <form method="POST" action="{% url 'watches:add_watch' %}" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% if form.errors %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <div id="form_errors">
                                {% for key, value in form.errors.items %}
                                    <strong>{{ value }}</strong>
                                {% endfor %}
                            </div>
                            <strong>{{ message|striptags }}</strong>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}

                    <div class="row" style="margin-top: 30px">
                        <div class="col">
                            <label class="mb-1">Brand*</label>
                            {{ form.brand }}
                        </div>
                        <div class="col">
                            <label class="mb-1">Model*</label>
                            {{ form.model }}
                        </div>
                    </div>
                    <div class="row" style="margin-top: 30px">
                        <div class="col">
                            <label class="mb-1">Reference Number</label>
                            {{ form.reference_number }}
                        </div>
                        <div class="col">
                            {% if form.year.errors %}
                                <label class="mb-1 alert-danger">Year</label>
                                {{ form.year }}
                            {% else %}
                                <label class="mb-1">Year</label>
                                {{ form.year }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="row" style="margin-top: 30px">
                        <div class="col">
                            <label class="mb-1">Style*</label>
                            {{ form.style }}
                        </div>
                        <div class="col">
                            {% if form.price_paid.errors %}
                                <label class="mb-1 alert-danger">Price Paid in EUR</label>
                                {{ form.price_paid }}
                            {% else %}
                                <label class="mb-1">Price Paid in EUR</label>
                                {{ form.price_paid }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="row" style="margin-top: 30px">
                        <div class="col">
                            <label class="mb-1">Condition</label>
                            {{ form.condition }}
                        </div>
                    </div>
                    <div class="row" style="margin-top: 30px">
                        <div class="col">
                            <label class="mb-1">Description</label>
                            {{ form.description }}
                        </div>
                    </div>
                    <div class="row" style="margin-top: 30px">
                        <div class="col">
                            <label class="mb-1">Image</label>
                            {{ form.image }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-warning" style="margin-top: 30px">Add</button>
                    <button type="button" onclick="location.href='{% url 'watches:show_all_watches' %}'"
                            class="btn btn-secondary flex-grow-1" style="margin-top: 30px">Cancel
                    </button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

chronos/watches/templates/watches/delete.html
{% extends 'web/base.html' %}

{% block content %}
        <div class="row d-flex justify-content-center" style="margin-top: 30px">
            <div class="col-md-5">
                <form id="delete" method="POST" action="{% url 'watches:delete_watch' watch.id %}">
                    <div class="container">
                        <h3>Are you sure you want to delete this watch?</h3>
                        {% csrf_token %}
                        {{ form }}
                        <input class="btn btn-danger flex-grow-1" type="submit" value="Delete Watch" style="margin-top: 20px">
                        <button type="button" onclick="location.href='{% url 'watches:show_all_watches' %}'"
                                class="btn btn-secondary flex-grow-1" style="margin-top: 20px">Cancel
                        </button>
                    </div>
                </form>
            </div>
        </div>

{% endblock %}

chronos/watches/templates/watches/details.html
{% extends 'web/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
    <div class="container-sm" style="margin-top: 30px">
        <div class="row">
            <div class="col-8 text-center">
                <figure class="figure border">
                    {% if watch.image %}
                        <img src="{{ watch.image.url }}" class="figure-img img-fluid"
                             style="object-fit: cover; height: 500px" alt="{{ watch.brand }}">
                    {% else %}
                        <img src="/media/watch/default_watch.png" class="figure-img img-fluid"
                             style="object-fit: cover; height: 500px" alt="{{ watch.brand }}">
                    {% endif %}
                </figure>
            </div>

            <div class="col-4">
                <h5><span class="badge bg-warning"
                          style="margin-bottom: 10px">Total Likes: {{ like_count }}</span></h5>
                <p><b>Brand: </b>{{ watch.brand }}</p>
                <p><b>Model: </b>{{ watch.model }}</p>
                <p><b>Reference Number: </b>{% if watch.reference_number %}{{ watch.reference_number }}{% endif %}</p>
                <p><b>Year: </b>{% if watch.year %}{{ watch.year }}{% endif %}</p>
                <p><b>Style: </b>{{ watch.style }}</p>
                <p><b>Condition: </b>{% if watch.condition %}{{ watch.condition }}{% endif %}</p>
                <p><b>Description: </b>{% if watch.description %}{{ watch.description }}{% endif %}</p>

                <div>
                    {% if request.user.is_authenticated %}
                        <form method="POST" action="{% url 'watches:like_watch' watch.id %}">
                            {% csrf_token %}
                            {% if not liked %}
                                <button type="submit" name="watch_id" value="watch.id" class="btn btn-warning">Like
                                </button>
                            {% else %}
                                <button type="submit" name="watch_id" value="watch.id" class="btn btn-danger">Dislike
                                </button>
                            {% endif %}
                        </form>
                    {% endif %}

                    <div style="margin-top: 15px">
                        {% if request.user.is_authenticated and request.user == watch.owner %}
                            <a href="{% url 'watches:edit_watch' watch.id %}"
                               class="btn btn-warning"
                               style="position: relative;">Edit</a>
                            <a href="{% url 'watches:delete_watch' watch.id %}"
                               class="btn btn-outline-danger"
                               style="position: relative;">Delete</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-sm" style="margin-top: 50px; margin-bottom: 50px">
        <h6>Comments ({{ comment_count }})</h6>

        {% if not comments %}
            <h6>There are no comments yet.</h6>
        {% else %}
            {% for comment in comments %}
                <div class="card" style="margin-top: 10px">
                    <div class="card-header" style="background-color: #FFF1C6">
                        <span class="badge bg-warning" style="margin-right: 10px">{{ forloop.counter }}</span>
                        <small><b>{{ comment.author }}</b> said {{ comment.created_on|timesince }} ago</small>
                    </div>
                    <div class="card-body">
                        <blockquote class="blockquote mb-0">
                            <p style="font-size: small">{{ comment.body }}</p>
                        </blockquote>

                    </div>
                </div>
            {% endfor %}
        {% endif %}

        {% if request.user.is_authenticated %}
            <form method="POST" style="margin-top: 40px;">
                {% csrf_token %}
                {{ comment_form }}
                <button type="submit" class="btn btn-warning" style="margin-top: 10px">Submit</button>
            </form>
        {% endif %}
    </div>
{% endblock %}

chronos/watches/templates/watches/edit.html
{% extends 'web/base.html' %}

{% block content %}
    <div class="container" style="margin-top: 30px; margin-bottom: 50px">
        <div class="row justify-content-md-center">
            <div class="col-md-6">
                <h3>Edit watch details from your collection</h3>
                <form method="POST" action="{% url 'watches:edit_watch' watch.id %}" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="row" style="margin-top: 30px">
                        <div class="col">
                            <label class="mb-1">Brand*</label>
                            {{ form.brand }}
                        </div>
                        <div class="col">
                            <label class="mb-1">Model*</label>
                            {{ form.model }}
                        </div>
                    </div>
                    <div class="row" style="margin-top: 30px">
                        <div class="col">
                            <label class="mb-1">Reference Number</label>
                            {{ form.reference_number }}
                        </div>
                        <div class="col">
                            <label class="mb-1">Year</label>
                            {{ form.year }}
                        </div>
                    </div>
                    <div class="row" style="margin-top: 30px">
                        <div class="col">
                            <label class="mb-1">Style*</label>
                            {{ form.style }}
                        </div>
                        <div class="col">
                            <label class="mb-1">Price Paid in EUR</label>
                            {{ form.price_paid }}
                        </div>
                    </div>
                    <div class="row" style="margin-top: 30px">
                        <div class="col">
                            <label class="mb-1">Condition</label>
                            {{ form.condition }}
                        </div>
                    </div>
                    <div class="row" style="margin-top: 30px">
                        <div class="col">
                            <label class="mb-1">Description</label>
                            {{ form.description }}
                        </div>
                    </div>
                    <div class="row" style="margin-top: 30px">
                        <div class="col">
                            <label class="mb-1">Image</label>
                            {{ form.image }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-warning" style="margin-top: 30px">Edit</button>
                    <button type="button" onclick="location.href='{% url 'watches:show_all_watches' %}'"
                            class="btn btn-secondary flex-grow-1" style="margin-top: 30px">Cancel
                    </button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

chronos/watches/templates/watches/show_collection.html
{% extends 'web/base.html' %}
{% load humanize %}


{% block content %}
    <div class="row d-flex justify-content-center" style="margin-top: 30px; margin-bottom: 50px">
        <div class="col-md-10">
            <h3 style="margin-bottom: 20px">My Collection</h3>

            <table class="table table-hover">
                <thead class="thead-dark table-warning">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Brand</th>
                    <th scope="col">Model</th>
                    <th scope="col">Reference Number</th>
                    <th scope="col">Year</th>
                    <th scope="col">Style</th>
                    <th scope="col">Likes</th>
                    <th scope="col">Price Paid</th>
                </tr>
                </thead>
                <tbody>

                {% for watch in watches %}
                    <tr onclick="window.location='{% url "watches:show_watch" watch.id %}';">
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ watch.brand }}</td>
                        <td>{{ watch.model }}</td>
                        <td>{% if watch.reference_number %}{{ watch.reference_number }}{% endif %}</td>
                        <td>{% if watch.year %}{{ watch.year }}{% endif %}</td>
                        <td>{{ watch.style }}</td>
                        <td>{{ watch.like_count }}</td>
                        <td>{% if watch.price_paid %}EUR {{ watch.price_paid|floatformat:2|intcomma }}{% endif %}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>

            <h5 style="text-align: right; margin-top: 25px">Total Paid: EUR {{ total_price_paid|floatformat:2|intcomma }}</h5>

        </div>
    </div>

{% endblock %}